### ISSUE TITLE
versione cracckata dubbi

### ISSUE THREAD

**Issue by piouzumaki** [lgiacomazzo/SG0-ITA#1]
ma questa patch non funziona sulla novel cracckata vero? la patch dei Coz si attiva ma nel gioco poi non si vedono i miglioramenti, quindi di conseguenza questa patch non si applica?

**Comment by lgiacomazzo** [comment]
avevo fatto dei test, controlla [qui](https://github.com/lgiacomazzo/SG0-ITA/tree/master/Per%20copie%20di%20backup%20e%20patch%202.0%20e%20dopo), dovrebbe funzionare.
A scanso di equivoci, consiglio di comprare la VN su Steam e evitare problemi dovuti a versioni craccate.

**Comment by piouzumaki** [comment]
ciao! ho mandato il mio file di sg0 ad una mia amica e non so perchè la patch ita non si applicava, ho reinstallato tutto, ho provato sia con 2.1 che con 2.1.2 seguendo gli stessi identici passaggi che ho fatto io ma niente, rimane sempre in inglese... non ho proprio idea di quale sia il problema

**Comment by lgiacomazzo** [comment]
Prova così:
1. Installa la VN in un path (ad esempio D:\Games\Steins;Gate 0)
2. Installa la patch dei CoZ (la 2.1.2, ed è importante che nel path di installazione ci sia "Steins;Gate 0")
3. Copia la mia traduzione (l'ultima release per renderla funzionante per la 2.1.2)

Dovrebbe funzionare.

**Comment by piouzumaki** [comment]
abbiamo risolto grazie mille!

**Comment by lgiacomazzo** [comment]
Bene 👍 
Chiudo questo issue allora.
